name: pyslim
channels:
  - conda-forge
  - bioconda
dependencies:
  - jupyterlab
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - msprime
  - pip
  - slim=5
  - tskit
  - pip:
    - git+https://github.com/tskit-dev/pyslim.git@740dc70
